//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmaMute.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmaMute.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust umamusume&apos;s volume automatically.
        /// </summary>
        internal static string MenuItem_MainConfig_EnableThisApp {
            get {
                return ResourceManager.GetString("MenuItem.MainConfig.EnableThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch umamusume automatically when UmaMute has launched.
        /// </summary>
        internal static string MenuItem_MainConfig_LaunchUmamusumeWhenUmaMuteHasLaunched {
            get {
                return ResourceManager.GetString("MenuItem.MainConfig.LaunchUmamusumeWhenUmaMuteHasLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate UmaMute.
        /// </summary>
        internal static string MenuItem_Terminate {
            get {
                return ResourceManager.GetString("MenuItem.Terminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value.
        /// </summary>
        internal static string MenuItem_Volume_CurrentValue {
            get {
                return ResourceManager.GetString("MenuItem.Volume.CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set current volume for umamusume on Volume mixer as this volume.
        /// </summary>
        internal static string MenuItem_Volume_CurrentVolume_Description {
            get {
                return ResourceManager.GetString("MenuItem.Volume.CurrentVolume.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current volume.
        /// </summary>
        internal static string MenuItem_Volume_CurrentVolume_Title {
            get {
                return ResourceManager.GetString("MenuItem.Volume.CurrentVolume.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume for umamusume when background.
        /// </summary>
        internal static string MenuItem_VolumeForBackground {
            get {
                return ResourceManager.GetString("MenuItem.VolumeForBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume for umamusume when foreground.
        /// </summary>
        internal static string MenuItem_VolumeForForeground {
            get {
                return ResourceManager.GetString("MenuItem.VolumeForForeground", resourceCulture);
            }
        }
    }
}
